In [1]:
from nav2_simple_commander.robot_navigator import BasicNavigator
import rclpy

rclpy.init()
nav = BasicNavigator()

In [2]:
nav.waitUntilNav2Active()

[INFO] [1704246269.139189525] [basic_navigator]: Nav2 is ready for use!


### 가고 싶은 것을 지정

In [3]:
from geometry_msgs.msg import PoseStamped

goal_pose = PoseStamped()
goal_pose.header.frame_id = 'map'
goal_pose.header.stamp = nav.get_clock().now().to_msg()

goal_pose.pose.position.x = 1.6231005191802979
goal_pose.pose.position.y = 1.527397632598877
goal_pose.pose.position.z = 0.002471923828125

goal_pose.pose.orientation.x = 0.0
goal_pose.pose.orientation.y = 0.0
goal_pose.pose.orientation.z = 0.0
goal_pose.pose.orientation.w = 1.0


### 가버렷

In [4]:
nav.goToPose(goal_pose)

[INFO] [1704246339.142936675] [basic_navigator]: Navigating to goal: -1.8196172714233398 0.23907724022865295...


True

### 상황을 피드백 받거나 오랫동안 이수하지 못하면 취소

In [5]:
from rclpy.duration import Duration

i = 0
while not nav.isTaskComplete():
    i += 1
    feedback = nav.getFeedback()

    if feedback and i % 5 ==0:
        print('Distance remaining: ' + '{:.2f}'.format(
            feedback.distance_remaining) + ' meters.')

        if Duration.from_msg(feedback.navigation_time) > Duration(seconds=10.0):
            nav.cancelTask()

Distance remaining: 0.66 meters.
Distance remaining: 0.60 meters.
Distance remaining: 0.60 meters.
Distance remaining: 0.00 meters.
Distance remaining: 0.52 meters.
Distance remaining: 0.52 meters.
Distance remaining: 0.47 meters.
Distance remaining: 0.47 meters.
Distance remaining: 0.37 meters.
Distance remaining: 0.32 meters.
Distance remaining: 0.27 meters.


### 상황 피드백 받기

In [6]:
from nav2_simple_commander.robot_navigator import TaskResult

result = nav.getResult()
if result == TaskResult.SUCCEEDED:
    print("goal succed")    
elif result == TaskResult.CANCELED:
    print('goal was canceled')
elif result == TaskResult.FAILED:
    print('goal failed')

goal succed


In [3]:
import rclpy
from geometry_msgs.msg import PoseWithCovarianceStamped

pose_current = PoseWithCovarianceStamped()
pose_current

geometry_msgs.msg.PoseWithCovarianceStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=0, nanosec=0), frame_id=''), pose=geometry_msgs.msg.PoseWithCovariance(pose=geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=0.0, y=0.0, z=0.0), orientation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.0, w=1.0)), covariance=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])))

In [4]:
pose_current.pose.pose.position

geometry_msgs.msg.Point(x=0.0, y=0.0, z=0.0)

In [5]:
pose_current.pose.pose.orientation

geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.0, w=1.0)

In [10]:
pose_node = rclpy.create_node('sub_pose')

def callback(data):
    global pose_current
    print("============")
    print(data.pose.pose.position)
    print(data.pose.pose.orientation)
    pose_current = data
    print(pose_current)
print(pose_current)

geometry_msgs.msg.PoseWithCovarianceStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=0, nanosec=0), frame_id=''), pose=geometry_msgs.msg.PoseWithCovariance(pose=geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=0.0, y=0.0, z=0.0), orientation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=0.0, w=1.0)), covariance=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])))


[WARN] [1702356649.379076267] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.


In [11]:
pose_node.create_subscription(PoseWithCovarianceStamped, '/amcl_pose', callback, 10)

In [16]:
rclpy.spin_once(pose_node)

geometry_msgs.msg.Point(x=1.719966525698393, y=-0.13100219533947693, z=0.0)
geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=-0.9775468038424824, w=0.2107184052173593)
geometry_msgs.msg.PoseWithCovarianceStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=217, nanosec=953000000), frame_id='map'), pose=geometry_msgs.msg.PoseWithCovariance(pose=geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=1.719966525698393, y=-0.13100219533947693, z=0.0), orientation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=-0.9775468038424824, w=0.2107184052173593)), covariance=array([1.95809212e-02, 3.04577308e-05, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.04577308e-05, 3.45523487e-02,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.0000

In [1]:
from tf_transformations import euler_from_quaternion

In [17]:
pose_current

geometry_msgs.msg.PoseWithCovarianceStamped(header=std_msgs.msg.Header(stamp=builtin_interfaces.msg.Time(sec=217, nanosec=953000000), frame_id='map'), pose=geometry_msgs.msg.PoseWithCovariance(pose=geometry_msgs.msg.Pose(position=geometry_msgs.msg.Point(x=1.719966525698393, y=-0.13100219533947693, z=0.0), orientation=geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=-0.9775468038424824, w=0.2107184052173593)), covariance=array([1.95809212e-02, 3.04577308e-05, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.04577308e-05, 3.45523487e-02,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.000

In [18]:
pose_current.pose.pose.orientation

geometry_msgs.msg.Quaternion(x=0.0, y=0.0, z=-0.9775468038424824, w=0.2107184052173593)

In [2]:
q = [0, 0, 0, 1]
# q[0] = pose_current.pose.pose.orientation.x
# q[1] = pose_current.pose.pose.orientation.y
# q[2] = pose_current.pose.pose.orientation.z
# q[3] = pose_current.pose.pose.orientation.w

euler_from_quaternion(q)

(0.0, -0.0, 0.0)

In [22]:
import numpy as np

def convert_degree(input):
    return np.array(input) * 180. /np.pi

convert_degree(euler_from_quaternion(q))

array([   0.        ,   -0.        , -155.67108812])

In [4]:
from tf_transformations import quaternion_from_euler
import numpy as np
to_radian = np.pi / 180.
tmp = [0.0 ,-0.0, 90.67108812]
print(np.array(tmp) * to_radian)

quaternion_from_euler(tmp[0], tmp[1], tmp[2])

[ 0.         -0.          1.58250902]


(0.0, 0.0, 0.9764293082836897, 0.21583745255315445)

In [21]:
from nav2_simple_commander.robot_navigator import BasicNavigator
from geometry_msgs.msg import PoseStamped

nav = BasicNavigator()

target = quaternion_from_euler(tmp[0], tmp[1], tmp[2])
goal_pose = PoseStamped()

goal_pose.header.frame_id = 'map'
goal_pose.header.stamp = nav.get_clock().now().to_msg()

goal_pose.pose.orientation.x = target[0]
goal_pose.pose.orientation.y = target[1]
goal_pose.pose.orientation.z = target[2]
goal_pose.pose.orientation.w = target[3]

[WARN] [1702354476.061145281] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.


In [22]:
from rclpy.duration import Duration

nav.goToPose(goal_pose)

i = 0

while not nav.isTaskComplete():
    i += 1
    feedback = nav.getFeedback()
    if feedback and i % 5 == 0:
        print('distance remaining' + '{:.2f}'.format(
            feedback.distance_remaining) + ' meters')
        
        if Duration.from_msg(feedback.navigation_time) > Duration(seconds=10.0):
            nav.cancelTask()


[INFO] [1702354485.371901561] [basic_navigator]: Navigating to goal: 0.0 0.0...


distance remaining2.18 meters
distance remaining2.18 meters
distance remaining2.18 meters
distance remaining2.18 meters
distance remaining2.18 meters
distance remaining2.18 meters
distance remaining2.18 meters
distance remaining2.13 meters
distance remaining2.13 meters
distance remaining2.12 meters
distance remaining2.12 meters
distance remaining2.12 meters
distance remaining2.12 meters
distance remaining2.12 meters
distance remaining2.08 meters
distance remaining2.08 meters
distance remaining2.06 meters
distance remaining2.06 meters
distance remaining2.02 meters
distance remaining0.00 meters
distance remaining0.00 meters
distance remaining0.00 meters
distance remaining0.00 meters
distance remaining0.00 meters
distance remaining0.00 meters
distance remaining0.00 meters
distance remaining0.00 meters
distance remaining0.00 meters
distance remaining0.00 meters
distance remaining0.00 meters
distance remaining0.00 meters
distance remaining0.00 meters
distance remaining0.00 meters
distance r

[INFO] [1702354507.085645198] [basic_navigator]: Canceling current task.


In [2]:
import numpy as np
input = [0., 0, 3.11]

degree = np.array(input) * 180. / np.pi
degree

array([  0.        ,   0.        , 178.18987429])

In [4]:
degree[1]

0.0